GENERAL:
  delay: 20
  noise: 0.2
INSTANTIATE:
  - name: b1
    type: B
    params:
      bg: red
      fg: green
    duration:
      mu: 7
      sigma: 0
  - name: b2
    type: B
    params:
      bg: red
      fg: green
    duration:
      mu: 7
      sigma: 0

RELATIONSHIP:
  - type: after
    events:
      - b1
      - b2
    other:
      gap_dist:
        mu: 4
        sigma: 1