PROJECT_FOLDER = "/home/S3G-LABS/u1226/dev/openchests/"
ENV_CONFIG_FOLDER = PROJECT_FOLDER + "config/"
ENV_PATTERNS_FOLDER = ENV_CONFIG_FOLDER + "patterns/"
EXCOG_EXP_FOLDER = PROJECT_FOLDER + "excog_experiments/"
