processing_sequence:
  - concurrent_techniques:
      - module: Process
        function: A2C_process
        params:
          gamma: 0.9
          normalize_advantage: False
          max_grad_norm: 0.3
          use_rms_prop: False
          gae_lambda: 0.8
          n_steps: 8
          learning_rate: 0.00001
          ent_coef: 0.00000000001
          vf_coef: 0
          ortho_init: False
          net_arch: "small"
          activation_fn: "tanh"
        global: monitor_file

      - module: Process
        function: PPO_process
        params:
          param1: pass
        global: monitor_file

    shared_params:
      param2: pass
    shared_data:
      - data1

global:
  monitor_file: "temp/<RUID>/"


datasets:
  data1: !raw_file ./data



