EVENT_TYPES:
  NORMAL:
    - A
    - B
    - C
  NOISE:
    - D
    - E
    - F
EVENT_ATTRIBUTES:
  NORMAL:
    fg:
      - red
      - blue
      - green
    bg:
      - red
      - blue
      - green
  NOISE:
    fg:
      - yellow
      - purple
      - black
    bg:
      - yellow
      - purple
      - black
INSTRUCTIONS:
  - similar_simple.yaml
  - simple.yaml