GENERAL:
  delay: 3
  noise: 0.2
INSTANTIATE:
  - name: d1
    type: D
    params:
      bg: green
      fg: green
    duration:
      mu: 10
      sigma: 2
  - name: d2
    type: D
    params:
      bg: green
      fg: green
    duration:
      mu: 10
      sigma: 2

RELATIONSHIP:
  - type: after
    events:
      - d1
      - d2
    other:
      gap_dist:
        mu: 4
        sigma: 1