EVENT_TYPES:
  NORMAL:
    - A
    - B
    - C
    - D
    - E
  NOISE:
    - G
    - H
    - F
EVENT_ATTRIBUTES:
  NORMAL:
    fg:
      - red
      - blue
      - green
      - orange
      - pink
    bg:
      - red
      - blue
      - green
      - orange
      - pink
  NOISE:
    fg:
      - yellow
      - purple
      - black
    bg:
      - yellow
      - purple
      - black
INSTRUCTIONS:
  - one_distinct_per_box/A.yaml
  - one_distinct_per_box/B.yaml
  - one_distinct_per_box/C.yaml