processing_sequence:
  - concurrent_techniques:
      - module: Process
        function: A2C_process
        params:
          normalize_advantage: False
          max_grad_norm: 0.3
          use_rms_prop: False
          ent_coef: 0.00000000001
          vf_coef: 0
        global: monitor_file

      - module: Process
        function: PPO_process
        params:
          batch_size: 8
          ent_coef: 0.1
          clip_range: 0.4
          n_epochs: 10
          max_grad_norm: 0.5
          vf_coef: 0
        global: monitor_file

      - module: Process
        function: TRPO_process
        params:
          batch_size: 16
          n_critic_updates:  10
          cg_max_steps: 20
          target_kl: 0.05
        global: monitor_file

    shared_params:
      gamma: 0.95
      gae_lambda: 0.8
      n_steps: 8
      learning_rate: 0.00001
      ortho_init: False
      net_arch: "small"
      activation_fn: "tanh"
    shared_data:
      - data1


global:
  monitor_file: "temp/<RUID>/"


datasets:
  data1: !raw_file ./data



